# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Di Hei
tagline:             'Thoughts on Technology and Everything Else'
description:         'Blog of Di Hei'
url:                 'http:diheiblog.com'
baseurl:             ''
gems:                [jekyll-paginate]
paginate:            2

# About/contact
author:
  name:              Di Hei
  url:               'https://github.com/dhei'
  email:             

# Custom vars
version:             1.0.0

highlighter:         pygments
